codecov:
  branch: master

coverage:
  precision: 2
  round: nearest
  range: 80..100
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
        if_not_found: success
        informational: false
        only_pulls: false
      core:
        paths:
          - ./packages/core/**
      user:
        paths:
          - ./apps/server/user/**
      article:
        paths:
          - ./apps/server/article/**
