version: '3.8'

services:
  server:
    container_name: conduit-local
    build:
      context: .
      dockerfile: ./apps/local/Dockerfile
    ports:
      - "3100:3100"
    command: node apps/local/local.js
    environment:
      - NODE_ENV=develop
      - MODE=local
      - DOMAIN=localhost
      - AUTH_JWT_SECRET=how-do-you-turn-this-on-in-2024
      - AUTH_JWT_EXPIRES_IN=1d
      - DATABASE_HOST=conduit-mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=conduit
      - DATABASE_PASSWORD=how-do-you-turn-this-on-twice
      - DATABASE_NAME=conduit-local
    depends_on:
      - mysql
      - db-migration

  mysql:
    image: mysql:8.0
    container_name: conduit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: how-do-you-turn-this-on 
      MYSQL_DATABASE: conduit-local        
      MYSQL_USER: conduit
      MYSQL_PASSWORD: how-do-you-turn-this-on-twice      
    ports:
      - "3306:3306"

  db-migration:
    container_name: conduit-db-migration
    command: ["yarn", "db:migrate"]
    build:
      context: .
      dockerfile: ./packages/core/database/Dockerfile
    environment:
      - NODE_ENV=develop
      - DATABASE_HOST=conduit-mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=conduit
      - DATABASE_PASSWORD=how-do-you-turn-this-on-twice
      - DATABASE_NAME=conduit-local
    depends_on:
      - mysql
