AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: >
  The AWS SAM application for Conduit consists of multiple deployment templates that define the resources and services used by the application

Resources:
  HealthCheck:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./
