name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master

jobs:
  #
  install-node:
    name: Install Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Cache the PNPM Store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  #
  spell-check:
    name: Spell Checking
    runs-on: ubuntu-latest
    needs: ["install-node"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Restore the PNPM Store Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check Spelling
        run: npm run spell-check


  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: ["install-node"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Restore the PNPM Store Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Unit Tests
        run: npm run test

  #
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: ["install-node"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Restore the PNPM Store Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint the Program
        run: npm run lint
