name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md" # Ignore changes to markdown files

jobs:
  e2e-test:
    name: End To End Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_USER: mysql
          MYSQL_DATABASE: conduit
        ports:
          - 3306:3306
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn" # Cache Yarn dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile # Ensures dependencies match yarn.lock
      - name: Run Database Migration
        run: yarn db:migrate
      - name: Build Application
        run: yarn build
      - name: Start Server in the Background
        run: yarn start:ci --filter=@conduit/local
      - name: Wait for the Server to Start
        run: ./scripts/wait-for-readiness.sh
      - name: Install Newman
        run: npm install -g newman
      - name: Run Integration Test
        run: ./scripts/api-test.sh

  deploy:
    name: Deploy to Production
    environment:
      name: production
    runs-on: ubuntu-latest
    needs: e2e-test
    steps:
      - name: Trigger AWS CodePipeline
        run: aws codepipeline start-pipeline-execution --name ${{
          vars.CODE_BUILD_PIPELINE }} --region ${{ vars.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  release:
    name: Release
    needs: e2e-test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow action to push to github
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
